### PR TITLE
fix openapi model composition

### LINKED ISSUE #10: Missing model composition references in OpenAPI schema
I am no expert in OpenAPI schema but I am wondering if the STAC API extensions such as Filter do not miss the reference to the base schema they extent as well as the paths were they are applicable.

refs: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

For instance:

```
schemas:
    searchBody:
      type: object
      x-stac-api-fragment: filter
      description: |-
        **Extension:** Filter
        A filter for properties in Items.
      properties:
        filter:
          $ref: '#/components/schemas/filter-cql2-json'
        filter-lang:
          $ref: '#/components/schemas/filter-lang'
        filter-crs:
          $ref: '#/components/schemas/filter-crs'
```

should actually be

```
schemas:
  searchBody:
    type: object
    x-stac-api-fragment: filter
    description: |-
      **Extension:** Filter
      A filter for properties in Items.
    allOf: # Combines the searchBody of Item-filter and the inline model
      - $ref: "https://api.stacspec.org/v1.0.0-rc.2/item-search/openapi.yaml#/components/schemas/searchBody"
    properties:
      filter:
        $ref: "#/components/schemas/filter-cql2-json"
      filter-lang:
        $ref: "#/components/schemas/filter-lang"
      filter-crs:
        $ref: "#/components/schemas/filter-crs"
```

and even if it defines a new data structure, the path using it should be specified again in order to specify which route accepts the new or extended structure
```
paths:
  /search:
    post:
      summary: Search STAC items with full-featured filtering.
      operationId: postItemSearch
      tags:
        - Item Search
        - Filter extension
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchBody'
```

On my side, without those specifications, the OpenAPI SDK generator cannot link the extension with any of the core APIs.

Let me know If I am missing something...

### PR DESCRIPTION
**Pull request by philvarner**
**Related Issue(s):** 

- https://github.com/stac-api-extensions/filter/issues/10

**Proposed Changes:**

1. Fix openapi model composition

**PR Checklist:**

- [X] This PR has **no** breaking changes.
- [X] I have added my changes to the [CHANGELOG](https://github.com/stac-api-extensions/filter/blob/main/CHANGELOG.md) **or** a CHANGELOG entry is not required.

### CODE REVIEW

**Review by emmanuelmathot — CHANGES_REQUESTED** [review]
Doesn't it apply to the Item Search endpoint (`/search`) too?

```suggestion
    /search:
      get:
        summary: Search STAC items with full-featured filtering.
        operationId: getItemSearch
        description: |-
          Retrieve Items matching filters. Intended as a shorthand API for simple
          queries.
          This method is required to implement.
          If this endpoint is implemented on a server, it is required to add a
          link referring to this endpoint with `rel` set to `search` to the
          `links` array in `GET /`. As `GET` is the default method, the `method`
          may not be set explicitly in the link.
        tags:
          - Item Search
          - Filter Extension
        parameters:
          - $ref: '#/components/parameters/filter'
          - $ref: '#/components/parameters/filter-lang'
          - $ref: '#/components/parameters/filter-crs'
        responses:
          '200':
            description: A feature collection.
            content:
              application/geo+json:
                schema:
                  $ref: '#/components/schemas/itemCollection'
              text/html:
                schema:
                  type: string
          '4XX':
            $ref: '#/components/responses/Error'
          '5XX':
            $ref: '#/components/responses/Error'
      post:
        summary: Search STAC items with full-featured filtering.
        operationId: postItemSearch
        description: |-
          Retrieve items matching filters. Intended as the standard, full-featured
          query API.
          This method is optional to implement, but recommended.
          If this endpoint is implemented on a server, it is required to add a
          link referring to this endpoint with `rel` set to `search` and `method`
          set to `POST` to the `links` array in `GET /`.
        tags:
          - Item Search
          - Filter Extension
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchBody'
        responses:
          '200':
            description: A feature collection.
            content:
              application/geo+json:
                schema:
                  $ref: '#/components/schemas/itemCollection'
              text/html:
                schema:
                  type: string
          '4XX':
            $ref: '#/components/responses/Error'
          '5XX':
            $ref: '#/components/responses/Error'
```

**Comment by philvarner** [comment]
The Features /items endpoint is also missing from this spec.

**Review by matthewhanson — DISMISSED** [review]

**Review by gadomski — APPROVED** [review]

**Comment by philvarner** [comment]
@emmanuelmathot could you take a look at this again?

**Review by emmanuelmathot — APPROVED** [review]
That works for me. I tested on the code gen and it is fine. Thx

**Pull request merged**
